feat: 로그인 / 로그아웃 / 회원가입 / 배지 / 북마크 / 마이페이지 기능 추가 및 프론트 디테일 수정
Supernova-QQ/Supernova pull request #70
Opened 2024-11-30 11:11 UTC by YewonParkk

## 🚀 연관된 이슈

> - resolve: #59 #46 #48 #16

## ✨ 작업 내용

> 로그인 페이지
- 로그인 시 AccessToken(1시간 유효, localStorage에서 관리함) / RefreshToken(일주일 유효,Cookie&Redis에서 관리함)을 생성하며 AccessToken이 만료되면 RefreshToken을 통해 재발급되는 로직 추가함
<img width="800" alt="image" src="https://github.com/user-attachments/assets/bc45bb66-ef4d-4cca-bd62-24f3737dd484">
     - 비밀번호 틀렸을 때 alert
     ![image](https://github.com/user-attachments/assets/ac134f75-07cd-4e8e-8201-51a635b4a2cc)

     - 로그인 성공 시 alert
     ![image](https://github.com/user-attachments/assets/b495ad84-22f2-4f4c-922c-589ce02e3041)
     
     - 로그인 성공 시 header 요소 변경됨
     <img width="800" alt="image" src="https://github.com/user-attachments/assets/f8224f2a-dd92-4389-846d-af5827af392e">

> 로그아웃
- 로그아웃 시 AccessToken과 RefreshToken이 모두 삭제되도록 처리함
<img width="800" alt="image" src="https://github.com/user-attachments/assets/42b2fa6d-5ab0-4f2f-b05c-0ffb30ecfb6b">

- 회원가입
<img width="800" alt="image" src="https://github.com/user-attachments/assets/07bb9ebd-6b02-4724-a7ba-f35021fadc5e">

> 배지 부여 CRUD
- 배지 부여 기준에 충족했을 시 배지가 부여됨(마이페이지에서 조회 가능함)
![image](https://github.com/user-attachments/assets/47a7af4f-208a-4ec5-893d-73d68ecb7bea)

> 북마크
     - CRUD 및 질문 페이지에서 질문과 답변에 아이콘 표시
     <img width="800" alt="image" src="https://github.com/user-attachments/assets/80a5e957-7448-48c5-b0a1-cbf27023976c">
     - 북마크 여부에 따라 아이콘 색상 변경됨
     <img width="800" alt="image" src="https://github.com/user-attachments/assets/20a1a066-d453-41dc-9f08-ad6caeb7f3f6">
     - 커뮤니티 내부의 내 노트 선택 시 로그인한 유저의 질문 / 답변 별로 북마크 목록 표시
     <img width="800" alt="image" src="https://github.com/user-attachments/assets/46be5dda-dd3a-4a15-a7c4-38acb6191ea1">

> 마이페이지
- 좌측 : 내가 속한 커뮤니티의 이미지와 커뮤니티명, 커뮤니티 설명이 카드 형태로 표시되며 해당 커뮤니티로 이동함
- 중앙 : 내 질문 조회 / 내 답변 조회 시 글 제목과 커뮤니티 이미지가 불러와짐 → 해당 글로 이동하는 코드 추가해야함
- 우측 : 회원 프로필과 함께 회원명이 표시되며 부여받은 배지 목록이 나타남 → 프로필 아래에 프로필 설정과 커뮤니티 관리 버튼이 추가될 예정
<img width="800" alt="image" src="https://github.com/user-attachments/assets/526e44bf-0035-4262-9c19-9466dc728291">

## 💬 리뷰 요구사항(주요 변경사항)
- **기존 X-QQ-AUTH-TOKEN을 X-QQ-ACCESS-TOKEN으로 변경함**
- fetch로 작성된 코드 중 사용자의 토큰으로 정보를 불러오거나 검증이 필요한 로직을 **fetchWithAuth**로 변경하여 페이지를 이동하도록 함.
- 로그인 / 회원가입 / 메인페이지 / 커뮤니티 메인 페이지 등은 로그인(토큰 검증)을 하지 않아도 이동할 수 있으며, 이외의 페이지는 로그인하지 않은 유저는 이동할 수 없음.
- **현재 로컬에서 테스트 가능한 상태로 config.js 파일의 BASE_URL을 수정해둔 상태입니다.**

2024-12-05 09:03 UTC, OhHaneol requested changes
너무 고생했어 예원아~!!! 다음 내용만 확인 부탁할게🩷

1. 변경사항이나 리뷰가 조금 많은데, 웹에서 고칠 수 있는 간단한 것들은 먼저 고치고, 만약 로직에 이동이 필요하다거나 하는 복잡한 작업은 그 이후에 로컬의 작업한 브랜치에서 변경사항 pull 한 다음에 고치고, 같은 브랜치에 commit&push 하면 될 거야!
2. 그리고 필요 없는 파일 삭제 부탁해!
3. 프론트는 아직 확인 안 했는데(잘 했을 것 같음), 수정사항 모두 반영하고 다시 리뷰 요청해주면 내가 승인 버튼 누를게! 그 후에 새로운 PR(test -> develop) 만들어주면 내가 해당 test 파일을 로컬에서 pull 해서 직접 돌려보면서 확인해보려구~!

2024-12-05 09:06 UTC, OhHaneol commented on src/main/resources/static/js/config.js
> +    // BASE_URL: 'http://13.124.80.116:8080',
테스트 할 때는 로컬로 해도, push 되는 파일의 url 은 항상 배포 상태로 되돌려놔주면 좋을 것 같아🩷
develop 에 병합되면 바로 배포되는 형태라서 서버에 오류가 날 수 있거든!

2024-12-11 06:43 UTC, YewonParkk commented on src/main/java/com/hanshin/supernova/SupernovaApplication.java
> +		// HikariCP 데이터소스 설정
아 이거 AccessToken 만료 시간 확인(서버시간과 로컬 시간의 차이 확인용) 때문에 추가했던건데 이제 삭제해도 되는 코드입니당!! 해당 코드와 관련 코드들도 삭제해둘게용!!

2024-12-11 06:43 UTC, YewonParkk commented on src/main/java/com/hanshin/supernova/ai_comment/application/AiAnswerService.java
> +import jakarta.servlet.http.HttpServletRequest;
네네! 확인했습니당!

2024-12-11 06:47 UTC, YewonParkk commented on src/main/java/com/hanshin/supernova/answer/application/AnswerService.java
호걱,,,  왜 저런,,,,, 거지,,,,, 당장 돌려놓을게요..!!🫠

2024-12-11 06:48 UTC, YewonParkk commented on src/main/java/com/hanshin/supernova/badge/application/BadgeService.java
> +        int bookmarkThreshold = 10; // 북마크 기준 수
아하!! 네네!! 훨씬 좋은 방법 알려주셔서 감사해용🥹

2024-12-11 06:52 UTC, YewonParkk commented on src/main/java/com/hanshin/supernova/badge/presentation/BadgeController.java
> +        // 2. 배지 부여 로직 실행
네네! 배지 현황이 마이페이지에서만 조회되고 있어서 마이페이지 접속 시 해당 경로가 실행되면서 배지 부여 후 배지 상태 반환하는 코드로 작성해뒀어용!

+그런데 배지가 부여됐을 때 알림이 가도록 하려면 조금 수정이 필요할 수 있겠단 생각이 드는...!😶‍🌫️😵‍💫

2024-12-11 06:53 UTC, YewonParkk commented on src/main/java/com/hanshin/supernova/bookmark/application/BookmarkServiceImpl.java
넵!!🫡

2024-12-11 06:54 UTC, YewonParkk commented on src/main/java/com/hanshin/supernova/bookmark/domain/Bookmark.java
> +    private BookmarkType type; // 질문인지 답변인지 구분
오앗 감사합니댜🥹🥹 저도 재PR 올릴 때 다시 한 번 확인하고 올릴게용!!

2024-12-11 12:36 UTC, YewonParkk commented on src/main/java/com/hanshin/supernova/hashtag/presentaion/HashtagController.java
> +import jakarta.servlet.http.HttpServletRequest;
settings>Editor>General>Auto Import>Optimize imports on the fly 옵션 켰습니당!! 이런 좋은 기능이 있는지 처음 알았,,,,,🥹

2024-12-11 12:51 UTC, YewonParkk commented on src/main/java/com/hanshin/supernova/question/application/QuestionService.java
언니,,, 죄송해요,,,,, 저 메소드,,, 마이페이지에서 내가 한 질문 목록 불러오면서 질문이 속한 커뮤니티 사진 불러오려고 커뮤니티 아이디 조회하는 메서드로 만들었던 거거든요...?
근데 my 패키지로 관련 코드 다 옮겼는데,,,, 저거만 옮기다가 빼먹고,,,, 안옮기고,,,, getQuestionsByUser 메서드로 새로 만들었나봐요🫠😭

아래 getQuestionsByUser 메서드랑 QuestionRepository에서 findCommunityIdByQuestionId 메서드 삭제했습니다ㅠㅠㅠㅠ 꼼꼼히 확인해주셔서 감사해요🥺🫶

2024-12-11 12:52 UTC, YewonParkk commented on src/main/java/com/hanshin/supernova/question/presentation/QuestionController.java
> +    // questionId로 communityId 조회
위에서 설명한 것처럼,,, 삭제되어 마땅한 메소드,,,,, 빠르게 삭제해버려습니다,,,,,⭐️

2024-12-11 13:05 UTC, YewonParkk commented on build.gradle
> +	implementation 'com.github.codemonstur:embedded-redis:1.4.3'
아뇨,,, 없어요,,,, 없어,,,,, 여기저기 찾아보며 얼렁뚱땅 하다가 바꿨었나봐요,,,, 기존 버전으로 사용해도 작동에 문제 없습니당!! 제대로 돌려놨어용!!ㅠㅠㅠㅠ

2024-12-11 13:08 UTC, YewonParkk commented on src/main/java/com/hanshin/supernova/redis/config/InMemoryRedisConfig.java
진짜 느낌표 백개,,,, 테스트용으로 작성했던건데,,, 고대로 올려버렸네요,,,, 이것 역시 빠른 삭제,,,🫠⭐️

2024-12-11 13:10 UTC, YewonParkk commented on src/main/resources/config/application-dev.yml
> +  cache:
맞아요 맞아,,,, 이것도 위에 InMemoryRedisConfig 테스트 하면서 적었던건데,,,, 바로 삭제⭐️

2024-12-11 13:12 UTC, YewonParkk commented on src/main/resources/static/js/config.js
> +    // BASE_URL: 'http://13.124.80.116:8080',
오엠지,,,,, 네네!!! 바꿨습니다!!!🥹

2024-12-12 14:56 UTC, closed without merging